//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;
#pragma warning disable 1591

namespace GmatClubTest.DbEditor.Data
{
    [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [DesignerCategory("code")]
    [ToolboxItem(true)]
    [XmlSchemaProvider("GetTypedDataSetSchema")]
    [XmlRoot("TestQuestionSetSet")]
    [HelpKeyword("vs.data.DataSet")]
    public partial class TestQuestionSetSet : DataSet
    {
        private TestsDataTable tableTests;

        private QuestionSetsDataTable tableQuestionSets;

        private TestContentsDataTable tableTestContents;

        private DataRelation relationTestsTestContents;

        private DataRelation relationQuestionSetsTestContents;

        private SchemaSerializationMode _schemaSerializationMode = SchemaSerializationMode.IncludeSchema;

        [DebuggerNonUserCode()]
        public TestQuestionSetSet()
        {
            BeginInit();
            InitClass();
            CollectionChangeEventHandler schemaChangedHandler = new CollectionChangeEventHandler(SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            EndInit();
        }

        [DebuggerNonUserCode()]
        protected TestQuestionSetSet(SerializationInfo info, StreamingContext context) :
            base(info, context, false)
        {
            if ((IsBinarySerialized(info, context) == true))
            {
                InitVars(false);
                CollectionChangeEventHandler schemaChangedHandler1 = new CollectionChangeEventHandler(SchemaChanged);
                Tables.CollectionChanged += schemaChangedHandler1;
                Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string) (info.GetValue("XmlSchema", typeof (string))));
            if ((DetermineSchemaSerializationMode(info, context) == SchemaSerializationMode.IncludeSchema))
            {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new StringReader(strSchema)));
                if ((ds.Tables["Tests"] != null))
                {
                    base.Tables.Add(new TestsDataTable(ds.Tables["Tests"]));
                }
                if ((ds.Tables["QuestionSets"] != null))
                {
                    base.Tables.Add(new QuestionSetsDataTable(ds.Tables["QuestionSets"]));
                }
                if ((ds.Tables["TestContents"] != null))
                {
                    base.Tables.Add(new TestContentsDataTable(ds.Tables["TestContents"]));
                }
                DataSetName = ds.DataSetName;
                Prefix = ds.Prefix;
                Namespace = ds.Namespace;
                Locale = ds.Locale;
                CaseSensitive = ds.CaseSensitive;
                EnforceConstraints = ds.EnforceConstraints;
                Merge(ds, false, MissingSchemaAction.Add);
                InitVars();
            }
            else
            {
                ReadXmlSchema(new XmlTextReader(new StringReader(strSchema)));
            }
            GetSerializationData(info, context);
            CollectionChangeEventHandler schemaChangedHandler = new CollectionChangeEventHandler(SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            Relations.CollectionChanged += schemaChangedHandler;
        }

        [DebuggerNonUserCode()]
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        public TestsDataTable Tests
        {
            get { return tableTests; }
        }

        [DebuggerNonUserCode()]
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        public QuestionSetsDataTable QuestionSets
        {
            get { return tableQuestionSets; }
        }

        [DebuggerNonUserCode()]
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        public TestContentsDataTable TestContents
        {
            get { return tableTestContents; }
        }

        [DebuggerNonUserCode()]
        [Browsable(true)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
        public override SchemaSerializationMode SchemaSerializationMode
        {
            get { return _schemaSerializationMode; }
            set { _schemaSerializationMode = value; }
        }

        [DebuggerNonUserCode()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public new DataTableCollection Tables
        {
            get { return base.Tables; }
        }

        [DebuggerNonUserCode()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public new DataRelationCollection Relations
        {
            get { return base.Relations; }
        }

        [DebuggerNonUserCode()]
        protected override void InitializeDerivedDataSet()
        {
            BeginInit();
            InitClass();
            EndInit();
        }

        [DebuggerNonUserCode()]
        public override DataSet Clone()
        {
            TestQuestionSetSet cln = ((TestQuestionSetSet) (base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = SchemaSerializationMode;
            return cln;
        }

        [DebuggerNonUserCode()]
        protected override bool ShouldSerializeTables()
        {
            return false;
        }

        [DebuggerNonUserCode()]
        protected override bool ShouldSerializeRelations()
        {
            return false;
        }

        [DebuggerNonUserCode()]
        protected override void ReadXmlSerializable(XmlReader reader)
        {
            if ((DetermineSchemaSerializationMode(reader) == SchemaSerializationMode.IncludeSchema))
            {
                Reset();
                DataSet ds = new DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Tests"] != null))
                {
                    base.Tables.Add(new TestsDataTable(ds.Tables["Tests"]));
                }
                if ((ds.Tables["QuestionSets"] != null))
                {
                    base.Tables.Add(new QuestionSetsDataTable(ds.Tables["QuestionSets"]));
                }
                if ((ds.Tables["TestContents"] != null))
                {
                    base.Tables.Add(new TestContentsDataTable(ds.Tables["TestContents"]));
                }
                DataSetName = ds.DataSetName;
                Prefix = ds.Prefix;
                Namespace = ds.Namespace;
                Locale = ds.Locale;
                CaseSensitive = ds.CaseSensitive;
                EnforceConstraints = ds.EnforceConstraints;
                Merge(ds, false, MissingSchemaAction.Add);
                InitVars();
            }
            else
            {
                ReadXml(reader);
                InitVars();
            }
        }

        [DebuggerNonUserCode()]
        protected override XmlSchema GetSchemaSerializable()
        {
            MemoryStream stream = new MemoryStream();
            WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return XmlSchema.Read(new XmlTextReader(stream), null);
        }

        [DebuggerNonUserCode()]
        internal void InitVars()
        {
            InitVars(true);
        }

        [DebuggerNonUserCode()]
        internal void InitVars(bool initTable)
        {
            tableTests = ((TestsDataTable) (base.Tables["Tests"]));
            if ((initTable == true))
            {
                if ((tableTests != null))
                {
                    tableTests.InitVars();
                }
            }
            tableQuestionSets = ((QuestionSetsDataTable) (base.Tables["QuestionSets"]));
            if ((initTable == true))
            {
                if ((tableQuestionSets != null))
                {
                    tableQuestionSets.InitVars();
                }
            }
            tableTestContents = ((TestContentsDataTable) (base.Tables["TestContents"]));
            if ((initTable == true))
            {
                if ((tableTestContents != null))
                {
                    tableTestContents.InitVars();
                }
            }
            relationTestsTestContents = Relations["TestsTestContents"];
            relationQuestionSetsTestContents = Relations["QuestionSetsTestContents"];
        }

        [DebuggerNonUserCode()]
        private void InitClass()
        {
            DataSetName = "TestQuestionSetSet";
            Prefix = "";
            Namespace = "http://tempuri.org/TestQuestionSetSet.xsd";
            EnforceConstraints = true;
            SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            tableTests = new TestsDataTable();
            base.Tables.Add(tableTests);
            tableQuestionSets = new QuestionSetsDataTable();
            base.Tables.Add(tableQuestionSets);
            tableTestContents = new TestContentsDataTable();
            base.Tables.Add(tableTestContents);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("TestsTestContents", new DataColumn[]
                                                                    {
                                                                        tableTests.IdColumn
                                                                    }, new DataColumn[]
                                                                           {
                                                                               tableTestContents.TestIdColumn
                                                                           });
            tableTestContents.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            fkc = new ForeignKeyConstraint("QuestionSetsTestContents", new DataColumn[]
                                                                           {
                                                                               tableQuestionSets.IdColumn
                                                                           }, new DataColumn[]
                                                                                  {
                                                                                      tableTestContents.
                                                                                          QuestionSetIdColumn
                                                                                  });
            tableTestContents.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            relationTestsTestContents = new DataRelation("TestsTestContents", new DataColumn[]
                                                                                  {
                                                                                      tableTests.IdColumn
                                                                                  }, new DataColumn[]
                                                                                         {
                                                                                             tableTestContents.
                                                                                                 TestIdColumn
                                                                                         }, false);
            Relations.Add(relationTestsTestContents);
            relationQuestionSetsTestContents = new DataRelation("QuestionSetsTestContents", new DataColumn[]
                                                                                                {
                                                                                                    tableQuestionSets.
                                                                                                        IdColumn
                                                                                                }, new DataColumn[]
                                                                                                       {
                                                                                                           tableTestContents
                                                                                                               .
                                                                                                               QuestionSetIdColumn
                                                                                                       }, false);
            Relations.Add(relationQuestionSetsTestContents);
        }

        [DebuggerNonUserCode()]
        private bool ShouldSerializeTests()
        {
            return false;
        }

        [DebuggerNonUserCode()]
        private bool ShouldSerializeQuestionSets()
        {
            return false;
        }

        [DebuggerNonUserCode()]
        private bool ShouldSerializeTestContents()
        {
            return false;
        }

        [DebuggerNonUserCode()]
        private void SchemaChanged(object sender, CollectionChangeEventArgs e)
        {
            if ((e.Action == CollectionChangeAction.Remove))
            {
                InitVars();
            }
        }

        [DebuggerNonUserCode()]
        public static XmlSchemaComplexType GetTypedDataSetSchema(XmlSchemaSet xs)
        {
            TestQuestionSetSet ds = new TestQuestionSetSet();
            XmlSchemaComplexType type = new XmlSchemaComplexType();
            XmlSchemaSequence sequence = new XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            XmlSchemaAny any = new XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }

        public delegate void TestsRowChangeEventHandler(object sender, TestsRowChangeEvent e);

        public delegate void QuestionSetsRowChangeEventHandler(object sender, QuestionSetsRowChangeEvent e);

        public delegate void TestContentsRowChangeEventHandler(object sender, TestContentsRowChangeEvent e);

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [Serializable()]
        [XmlSchemaProvider("GetTypedTableSchema")]
        public partial class TestsDataTable : DataTable, IEnumerable
        {
            private DataColumn columnId;

            private DataColumn columnName;

            private DataColumn columnIsPractice;

            private DataColumn columnDescription;

            private DataColumn columnQuestionTypeId;

            private DataColumn columnQuestionSubtypeId;

            private DataColumn columnGUID;

            private DataColumn columnVersion;

            [DebuggerNonUserCode()]
            public TestsDataTable()
            {
                TableName = "Tests";
                BeginInit();
                InitClass();
                EndInit();
            }

            [DebuggerNonUserCode()]
            internal TestsDataTable(DataTable table)
            {
                TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive))
                {
                    CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString()))
                {
                    Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace))
                {
                    Namespace = table.Namespace;
                }
                Prefix = table.Prefix;
                MinimumCapacity = table.MinimumCapacity;
            }

            [DebuggerNonUserCode()]
            protected TestsDataTable(SerializationInfo info, StreamingContext context) :
                base(info, context)
            {
                InitVars();
            }

            [DebuggerNonUserCode()]
            public DataColumn IdColumn
            {
                get { return columnId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NameColumn
            {
                get { return columnName; }
            }

            [DebuggerNonUserCode()]
            public DataColumn IsPracticeColumn
            {
                get { return columnIsPractice; }
            }

            [DebuggerNonUserCode()]
            public DataColumn DescriptionColumn
            {
                get { return columnDescription; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionTypeIdColumn
            {
                get { return columnQuestionTypeId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionSubtypeIdColumn
            {
                get { return columnQuestionSubtypeId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn GUIDColumn
            {
                get { return columnGUID; }
            }

            [DebuggerNonUserCode()]
            public DataColumn VersionColumn
            {
                get { return columnVersion; }
            }

            [DebuggerNonUserCode()]
            [Browsable(false)]
            public int Count
            {
                get { return Rows.Count; }
            }

            [DebuggerNonUserCode()]
            public TestsRow this[int index]
            {
                get { return ((TestsRow) (Rows[index])); }
            }

            public event TestsRowChangeEventHandler TestsRowChanging;

            public event TestsRowChangeEventHandler TestsRowChanged;

            public event TestsRowChangeEventHandler TestsRowDeleting;

            public event TestsRowChangeEventHandler TestsRowDeleted;

            [DebuggerNonUserCode()]
            public void AddTestsRow(TestsRow row)
            {
                Rows.Add(row);
            }

            [DebuggerNonUserCode()]
            public TestsRow AddTestsRow(string Name, bool IsPractice, string Description, int QuestionTypeId,
                                        int QuestionSubtypeId, string GUID, int Version)
            {
                TestsRow rowTestsRow = ((TestsRow) (NewRow()));
                rowTestsRow.ItemArray = new object[]
                    {
                        null,
                        Name,
                        IsPractice,
                        Description,
                        QuestionTypeId,
                        QuestionSubtypeId,
                        GUID,
                        Version
                    };
                Rows.Add(rowTestsRow);
                return rowTestsRow;
            }

            [DebuggerNonUserCode()]
            public TestsRow FindById(int Id)
            {
                return ((TestsRow) (Rows.Find(new object[]
                                                  {
                                                      Id
                                                  })));
            }

            [DebuggerNonUserCode()]
            public virtual IEnumerator GetEnumerator()
            {
                return Rows.GetEnumerator();
            }

            [DebuggerNonUserCode()]
            public override DataTable Clone()
            {
                TestsDataTable cln = ((TestsDataTable) (base.Clone()));
                cln.InitVars();
                return cln;
            }

            [DebuggerNonUserCode()]
            protected override DataTable CreateInstance()
            {
                return new TestsDataTable();
            }

            [DebuggerNonUserCode()]
            internal void InitVars()
            {
                columnId = base.Columns["Id"];
                columnName = base.Columns["Name"];
                columnIsPractice = base.Columns["IsPractice"];
                columnDescription = base.Columns["Description"];
                columnQuestionTypeId = base.Columns["QuestionTypeId"];
                columnQuestionSubtypeId = base.Columns["QuestionSubtypeId"];
                columnGUID = base.Columns["GUID"];
                columnVersion = base.Columns["Version"];
            }

            [DebuggerNonUserCode()]
            private void InitClass()
            {
                columnId = new DataColumn("Id", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnId);
                columnName = new DataColumn("Name", typeof (string), null, MappingType.Element);
                base.Columns.Add(columnName);
                columnIsPractice = new DataColumn("IsPractice", typeof (bool), null, MappingType.Element);
                base.Columns.Add(columnIsPractice);
                columnDescription = new DataColumn("Description", typeof (string), null, MappingType.Element);
                base.Columns.Add(columnDescription);
                columnQuestionTypeId = new DataColumn("QuestionTypeId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnQuestionTypeId);
                columnQuestionSubtypeId = new DataColumn("QuestionSubtypeId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnQuestionSubtypeId);
                columnGUID = new DataColumn("GUID", typeof (string), null, MappingType.Element);
                base.Columns.Add(columnGUID);
                columnVersion = new DataColumn("Version", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnVersion);
                Constraints.Add(new UniqueConstraint("KeyOfTests", new DataColumn[]
                                                                       {
                                                                           columnId
                                                                       }, true));
                columnId.AutoIncrement = true;
                columnId.AllowDBNull = false;
                columnId.ReadOnly = true;
                columnId.Unique = true;
                columnName.AllowDBNull = false;
                columnIsPractice.AllowDBNull = false;
                columnDescription.AllowDBNull = false;
                columnGUID.AllowDBNull = false;
                columnVersion.AllowDBNull = false;
            }

            [DebuggerNonUserCode()]
            public TestsRow NewTestsRow()
            {
                return ((TestsRow) (NewRow()));
            }

            [DebuggerNonUserCode()]
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
            {
                return new TestsRow(builder);
            }

            [DebuggerNonUserCode()]
            protected override Type GetRowType()
            {
                return typeof (TestsRow);
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanged(DataRowChangeEventArgs e)
            {
                base.OnRowChanged(e);
                if ((TestsRowChanged != null))
                {
                    TestsRowChanged(this, new TestsRowChangeEvent(((TestsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanging(DataRowChangeEventArgs e)
            {
                base.OnRowChanging(e);
                if ((TestsRowChanging != null))
                {
                    TestsRowChanging(this, new TestsRowChangeEvent(((TestsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleted(DataRowChangeEventArgs e)
            {
                base.OnRowDeleted(e);
                if ((TestsRowDeleted != null))
                {
                    TestsRowDeleted(this, new TestsRowChangeEvent(((TestsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleting(DataRowChangeEventArgs e)
            {
                base.OnRowDeleting(e);
                if ((TestsRowDeleting != null))
                {
                    TestsRowDeleting(this, new TestsRowChangeEvent(((TestsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            public void RemoveTestsRow(TestsRow row)
            {
                Rows.Remove(row);
            }

            [DebuggerNonUserCode()]
            public static XmlSchemaComplexType GetTypedTableSchema(XmlSchemaSet xs)
            {
                XmlSchemaComplexType type = new XmlSchemaComplexType();
                XmlSchemaSequence sequence = new XmlSchemaSequence();
                TestQuestionSetSet ds = new TestQuestionSetSet();
                xs.Add(ds.GetSchemaSerializable());
                XmlSchemaAny any1 = new XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                XmlSchemaAny any2 = new XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                XmlSchemaAttribute attribute1 = new XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                XmlSchemaAttribute attribute2 = new XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TestsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [Serializable()]
        [XmlSchemaProvider("GetTypedTableSchema")]
        public partial class QuestionSetsDataTable : DataTable, IEnumerable
        {
            private DataColumn columnId;

            private DataColumn columnName;

            private DataColumn columnDescription;

            private DataColumn columnNumberOfQuestionsToPick;

            private DataColumn columnTimeLimit;

            private DataColumn columnQuestionTypeId;

            private DataColumn columnQuestionSubtypeId;

            private DataColumn columnNumberOfQuestionsInZone1;

            private DataColumn columnNumberOfQuestionsInZone2;

            private DataColumn columnNumberOfQuestionsInZone3;

            [DebuggerNonUserCode()]
            public QuestionSetsDataTable()
            {
                TableName = "QuestionSets";
                BeginInit();
                InitClass();
                EndInit();
            }

            [DebuggerNonUserCode()]
            internal QuestionSetsDataTable(DataTable table)
            {
                TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive))
                {
                    CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString()))
                {
                    Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace))
                {
                    Namespace = table.Namespace;
                }
                Prefix = table.Prefix;
                MinimumCapacity = table.MinimumCapacity;
            }

            [DebuggerNonUserCode()]
            protected QuestionSetsDataTable(SerializationInfo info, StreamingContext context) :
                base(info, context)
            {
                InitVars();
            }

            [DebuggerNonUserCode()]
            public DataColumn IdColumn
            {
                get { return columnId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NameColumn
            {
                get { return columnName; }
            }

            [DebuggerNonUserCode()]
            public DataColumn DescriptionColumn
            {
                get { return columnDescription; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NumberOfQuestionsToPickColumn
            {
                get { return columnNumberOfQuestionsToPick; }
            }

            [DebuggerNonUserCode()]
            public DataColumn TimeLimitColumn
            {
                get { return columnTimeLimit; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionTypeIdColumn
            {
                get { return columnQuestionTypeId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionSubtypeIdColumn
            {
                get { return columnQuestionSubtypeId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NumberOfQuestionsInZone1Column
            {
                get { return columnNumberOfQuestionsInZone1; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NumberOfQuestionsInZone2Column
            {
                get { return columnNumberOfQuestionsInZone2; }
            }

            [DebuggerNonUserCode()]
            public DataColumn NumberOfQuestionsInZone3Column
            {
                get { return columnNumberOfQuestionsInZone3; }
            }

            [DebuggerNonUserCode()]
            [Browsable(false)]
            public int Count
            {
                get { return Rows.Count; }
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow this[int index]
            {
                get { return ((QuestionSetsRow) (Rows[index])); }
            }

            public event QuestionSetsRowChangeEventHandler QuestionSetsRowChanging;

            public event QuestionSetsRowChangeEventHandler QuestionSetsRowChanged;

            public event QuestionSetsRowChangeEventHandler QuestionSetsRowDeleting;

            public event QuestionSetsRowChangeEventHandler QuestionSetsRowDeleted;

            [DebuggerNonUserCode()]
            public void AddQuestionSetsRow(QuestionSetsRow row)
            {
                Rows.Add(row);
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow AddQuestionSetsRow(int id, string Name, string Description,
                                                      int NumberOfQuestionsToPick, int TimeLimit, int QuestionTypeId,
                                                      int QuestionSubtypeId, int NumberOfQuestionsInZone1,
                                                      int NumberOfQuestionsInZone2, int NumberOfQuestionsInZone3)
            {
                QuestionSetsRow rowQuestionSetsRow = ((QuestionSetsRow) (NewRow()));
                rowQuestionSetsRow.ItemArray = new object[]
                    {
                        id,
                        Name,
                        Description,
                        NumberOfQuestionsToPick,
                        TimeLimit,
                        QuestionTypeId,
                        QuestionSubtypeId,
                        NumberOfQuestionsInZone1,
                        NumberOfQuestionsInZone2,
                        NumberOfQuestionsInZone3
                    };
                Rows.Add(rowQuestionSetsRow);
                return rowQuestionSetsRow;
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow FindById(int Id)
            {
                return ((QuestionSetsRow) (Rows.Find(new object[]
                                                         {
                                                             Id
                                                         })));
            }

            [DebuggerNonUserCode()]
            public virtual IEnumerator GetEnumerator()
            {
                return Rows.GetEnumerator();
            }

            [DebuggerNonUserCode()]
            public override DataTable Clone()
            {
                QuestionSetsDataTable cln = ((QuestionSetsDataTable) (base.Clone()));
                cln.InitVars();
                return cln;
            }

            [DebuggerNonUserCode()]
            protected override DataTable CreateInstance()
            {
                return new QuestionSetsDataTable();
            }

            [DebuggerNonUserCode()]
            internal void InitVars()
            {
                columnId = base.Columns["Id"];
                columnName = base.Columns["Name"];
                columnDescription = base.Columns["Description"];
                columnNumberOfQuestionsToPick = base.Columns["NumberOfQuestionsToPick"];
                columnTimeLimit = base.Columns["TimeLimit"];
                columnQuestionTypeId = base.Columns["QuestionTypeId"];
                columnQuestionSubtypeId = base.Columns["QuestionSubtypeId"];
                columnNumberOfQuestionsInZone1 = base.Columns["NumberOfQuestionsInZone1"];
                columnNumberOfQuestionsInZone2 = base.Columns["NumberOfQuestionsInZone2"];
                columnNumberOfQuestionsInZone3 = base.Columns["NumberOfQuestionsInZone3"];
            }

            [DebuggerNonUserCode()]
            private void InitClass()
            {
                columnId = new DataColumn("Id", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnId);
                columnName = new DataColumn("Name", typeof (string), null, MappingType.Element);
                base.Columns.Add(columnName);
                columnDescription = new DataColumn("Description", typeof (string), null, MappingType.Element);
                base.Columns.Add(columnDescription);
                columnNumberOfQuestionsToPick =
                    new DataColumn("NumberOfQuestionsToPick", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnNumberOfQuestionsToPick);
                columnTimeLimit = new DataColumn("TimeLimit", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnTimeLimit);
                columnQuestionTypeId = new DataColumn("QuestionTypeId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnQuestionTypeId);
                columnQuestionSubtypeId = new DataColumn("QuestionSubtypeId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnQuestionSubtypeId);
                columnNumberOfQuestionsInZone1 =
                    new DataColumn("NumberOfQuestionsInZone1", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnNumberOfQuestionsInZone1);
                columnNumberOfQuestionsInZone2 =
                    new DataColumn("NumberOfQuestionsInZone2", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnNumberOfQuestionsInZone2);
                columnNumberOfQuestionsInZone3 =
                    new DataColumn("NumberOfQuestionsInZone3", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnNumberOfQuestionsInZone3);
                Constraints.Add(new UniqueConstraint("KeyOfQuestionSets", new DataColumn[]
                                                                              {
                                                                                  columnId
                                                                              }, true));
                columnId.AutoIncrement = true;
                columnId.AllowDBNull = false;
                columnId.ReadOnly = true;
                columnId.Unique = true;
                columnName.AllowDBNull = false;
                columnDescription.AllowDBNull = false;
                columnNumberOfQuestionsToPick.AllowDBNull = false;
                columnNumberOfQuestionsInZone1.AllowDBNull = false;
                columnNumberOfQuestionsInZone2.AllowDBNull = false;
                columnNumberOfQuestionsInZone3.AllowDBNull = false;
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow NewQuestionSetsRow()
            {
                return ((QuestionSetsRow) (NewRow()));
            }

            [DebuggerNonUserCode()]
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
            {
                return new QuestionSetsRow(builder);
            }

            [DebuggerNonUserCode()]
            protected override Type GetRowType()
            {
                return typeof (QuestionSetsRow);
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanged(DataRowChangeEventArgs e)
            {
                base.OnRowChanged(e);
                if ((QuestionSetsRowChanged != null))
                {
                    QuestionSetsRowChanged(this, new QuestionSetsRowChangeEvent(((QuestionSetsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanging(DataRowChangeEventArgs e)
            {
                base.OnRowChanging(e);
                if ((QuestionSetsRowChanging != null))
                {
                    QuestionSetsRowChanging(this, new QuestionSetsRowChangeEvent(((QuestionSetsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleted(DataRowChangeEventArgs e)
            {
                base.OnRowDeleted(e);
                if ((QuestionSetsRowDeleted != null))
                {
                    QuestionSetsRowDeleted(this, new QuestionSetsRowChangeEvent(((QuestionSetsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleting(DataRowChangeEventArgs e)
            {
                base.OnRowDeleting(e);
                if ((QuestionSetsRowDeleting != null))
                {
                    QuestionSetsRowDeleting(this, new QuestionSetsRowChangeEvent(((QuestionSetsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            public void RemoveQuestionSetsRow(QuestionSetsRow row)
            {
                Rows.Remove(row);
            }

            [DebuggerNonUserCode()]
            public static XmlSchemaComplexType GetTypedTableSchema(XmlSchemaSet xs)
            {
                XmlSchemaComplexType type = new XmlSchemaComplexType();
                XmlSchemaSequence sequence = new XmlSchemaSequence();
                TestQuestionSetSet ds = new TestQuestionSetSet();
                xs.Add(ds.GetSchemaSerializable());
                XmlSchemaAny any1 = new XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                XmlSchemaAny any2 = new XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                XmlSchemaAttribute attribute1 = new XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                XmlSchemaAttribute attribute2 = new XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "QuestionSetsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [Serializable()]
        [XmlSchemaProvider("GetTypedTableSchema")]
        public partial class TestContentsDataTable : DataTable, IEnumerable
        {
            private DataColumn columnTestId;

            private DataColumn columnQuestionSetId;

            private DataColumn columnQuestionSetOrder;

            [DebuggerNonUserCode()]
            public TestContentsDataTable()
            {
                TableName = "TestContents";
                BeginInit();
                InitClass();
                EndInit();
            }

            [DebuggerNonUserCode()]
            internal TestContentsDataTable(DataTable table)
            {
                TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive))
                {
                    CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString()))
                {
                    Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace))
                {
                    Namespace = table.Namespace;
                }
                Prefix = table.Prefix;
                MinimumCapacity = table.MinimumCapacity;
            }

            [DebuggerNonUserCode()]
            protected TestContentsDataTable(SerializationInfo info, StreamingContext context) :
                base(info, context)
            {
                InitVars();
            }

            [DebuggerNonUserCode()]
            public DataColumn TestIdColumn
            {
                get { return columnTestId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionSetIdColumn
            {
                get { return columnQuestionSetId; }
            }

            [DebuggerNonUserCode()]
            public DataColumn QuestionSetOrderColumn
            {
                get { return columnQuestionSetOrder; }
            }

            [DebuggerNonUserCode()]
            [Browsable(false)]
            public int Count
            {
                get { return Rows.Count; }
            }

            [DebuggerNonUserCode()]
            public TestContentsRow this[int index]
            {
                get { return ((TestContentsRow) (Rows[index])); }
            }

            public event TestContentsRowChangeEventHandler TestContentsRowChanging;

            public event TestContentsRowChangeEventHandler TestContentsRowChanged;

            public event TestContentsRowChangeEventHandler TestContentsRowDeleting;

            public event TestContentsRowChangeEventHandler TestContentsRowDeleted;

            [DebuggerNonUserCode()]
            public void AddTestContentsRow(TestContentsRow row)
            {
                Rows.Add(row);
            }

            [DebuggerNonUserCode()]
            public TestContentsRow AddTestContentsRow(TestsRow parentTestsRowByTestsTestContents,
                                                      QuestionSetsRow parentQuestionSetsRowByQuestionSetsTestContents,
                                                      byte QuestionSetOrder)
            {
                TestContentsRow rowTestContentsRow = ((TestContentsRow) (NewRow()));
                rowTestContentsRow.ItemArray = new object[]
                    {
                        parentTestsRowByTestsTestContents[0],
                        parentQuestionSetsRowByQuestionSetsTestContents[0],
                        QuestionSetOrder
                    };
                Rows.Add(rowTestContentsRow);
                return rowTestContentsRow;
            }

            [DebuggerNonUserCode()]
            public TestContentsRow FindByTestIdQuestionSetId(int TestId, int QuestionSetId)
            {
                return ((TestContentsRow) (Rows.Find(new object[]
                                                         {
                                                             TestId,
                                                             QuestionSetId
                                                         })));
            }

            [DebuggerNonUserCode()]
            public virtual IEnumerator GetEnumerator()
            {
                return Rows.GetEnumerator();
            }

            [DebuggerNonUserCode()]
            public override DataTable Clone()
            {
                TestContentsDataTable cln = ((TestContentsDataTable) (base.Clone()));
                cln.InitVars();
                return cln;
            }

            [DebuggerNonUserCode()]
            protected override DataTable CreateInstance()
            {
                return new TestContentsDataTable();
            }

            [DebuggerNonUserCode()]
            internal void InitVars()
            {
                columnTestId = base.Columns["TestId"];
                columnQuestionSetId = base.Columns["QuestionSetId"];
                columnQuestionSetOrder = base.Columns["QuestionSetOrder"];
            }

            [DebuggerNonUserCode()]
            private void InitClass()
            {
                columnTestId = new DataColumn("TestId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnTestId);
                columnQuestionSetId = new DataColumn("QuestionSetId", typeof (int), null, MappingType.Element);
                base.Columns.Add(columnQuestionSetId);
                columnQuestionSetOrder = new DataColumn("QuestionSetOrder", typeof (byte), null, MappingType.Element);
                base.Columns.Add(columnQuestionSetOrder);
                Constraints.Add(new UniqueConstraint("KeyOfTestContents", new DataColumn[]
                                                                              {
                                                                                  columnTestId,
                                                                                  columnQuestionSetId
                                                                              }, true));
                columnTestId.AllowDBNull = false;
                columnQuestionSetId.AllowDBNull = false;
                columnQuestionSetOrder.AllowDBNull = false;
            }

            [DebuggerNonUserCode()]
            public TestContentsRow NewTestContentsRow()
            {
                return ((TestContentsRow) (NewRow()));
            }

            [DebuggerNonUserCode()]
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
            {
                return new TestContentsRow(builder);
            }

            [DebuggerNonUserCode()]
            protected override Type GetRowType()
            {
                return typeof (TestContentsRow);
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanged(DataRowChangeEventArgs e)
            {
                base.OnRowChanged(e);
                if ((TestContentsRowChanged != null))
                {
                    TestContentsRowChanged(this, new TestContentsRowChangeEvent(((TestContentsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowChanging(DataRowChangeEventArgs e)
            {
                base.OnRowChanging(e);
                if ((TestContentsRowChanging != null))
                {
                    TestContentsRowChanging(this, new TestContentsRowChangeEvent(((TestContentsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleted(DataRowChangeEventArgs e)
            {
                base.OnRowDeleted(e);
                if ((TestContentsRowDeleted != null))
                {
                    TestContentsRowDeleted(this, new TestContentsRowChangeEvent(((TestContentsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            protected override void OnRowDeleting(DataRowChangeEventArgs e)
            {
                base.OnRowDeleting(e);
                if ((TestContentsRowDeleting != null))
                {
                    TestContentsRowDeleting(this, new TestContentsRowChangeEvent(((TestContentsRow) (e.Row)), e.Action));
                }
            }

            [DebuggerNonUserCode()]
            public void RemoveTestContentsRow(TestContentsRow row)
            {
                Rows.Remove(row);
            }

            [DebuggerNonUserCode()]
            public static XmlSchemaComplexType GetTypedTableSchema(XmlSchemaSet xs)
            {
                XmlSchemaComplexType type = new XmlSchemaComplexType();
                XmlSchemaSequence sequence = new XmlSchemaSequence();
                TestQuestionSetSet ds = new TestQuestionSetSet();
                xs.Add(ds.GetSchemaSerializable());
                XmlSchemaAny any1 = new XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                XmlSchemaAny any2 = new XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                XmlSchemaAttribute attribute1 = new XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                XmlSchemaAttribute attribute2 = new XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TestContentsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TestsRow : DataRow
        {
            private TestsDataTable tableTests;

            [DebuggerNonUserCode()]
            internal TestsRow(DataRowBuilder rb) :
                base(rb)
            {
                tableTests = ((TestsDataTable) (Table));
            }

            [DebuggerNonUserCode()]
            public int Id
            {
                get { return ((int) (this[tableTests.IdColumn])); }
                set { this[tableTests.IdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public string Name
            {
                get { return ((string) (this[tableTests.NameColumn])); }
                set { this[tableTests.NameColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public bool IsPractice
            {
                get { return ((bool) (this[tableTests.IsPracticeColumn])); }
                set { this[tableTests.IsPracticeColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public string Description
            {
                get { return ((string) (this[tableTests.DescriptionColumn])); }
                set { this[tableTests.DescriptionColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int QuestionTypeId
            {
                get
                {
                    try
                    {
                        return ((int) (this[tableTests.QuestionTypeIdColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException(
                            "The value for column \'QuestionTypeId\' in table \'Tests\' is DBNull.", e);
                    }
                }
                set { this[tableTests.QuestionTypeIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int QuestionSubtypeId
            {
                get
                {
                    try
                    {
                        return ((int) (this[tableTests.QuestionSubtypeIdColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException(
                            "The value for column \'QuestionSubtypeId\' in table \'Tests\' is DBNull.", e);
                    }
                }
                set { this[tableTests.QuestionSubtypeIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public string GUID
            {
                get { return ((string) (this[tableTests.GUIDColumn])); }
                set { this[tableTests.GUIDColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int Version
            {
                get { return ((int) (this[tableTests.VersionColumn])); }
                set { this[tableTests.VersionColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public bool IsQuestionTypeIdNull()
            {
                return IsNull(tableTests.QuestionTypeIdColumn);
            }

            [DebuggerNonUserCode()]
            public void SetQuestionTypeIdNull()
            {
                this[tableTests.QuestionTypeIdColumn] = Convert.DBNull;
            }

            [DebuggerNonUserCode()]
            public bool IsQuestionSubtypeIdNull()
            {
                return IsNull(tableTests.QuestionSubtypeIdColumn);
            }

            [DebuggerNonUserCode()]
            public void SetQuestionSubtypeIdNull()
            {
                this[tableTests.QuestionSubtypeIdColumn] = Convert.DBNull;
            }

            [DebuggerNonUserCode()]
            public TestContentsRow[] GetTestContentsRows()
            {
                return ((TestContentsRow[]) (base.GetChildRows(Table.ChildRelations["TestsTestContents"])));
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class QuestionSetsRow : DataRow
        {
            private QuestionSetsDataTable tableQuestionSets;

            [DebuggerNonUserCode()]
            internal QuestionSetsRow(DataRowBuilder rb) :
                base(rb)
            {
                tableQuestionSets = ((QuestionSetsDataTable) (Table));
            }

            [DebuggerNonUserCode()]
            public int Id
            {
                get { return ((int) (this[tableQuestionSets.IdColumn])); }
                set { this[tableQuestionSets.IdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public string Name
            {
                get { return ((string) (this[tableQuestionSets.NameColumn])); }
                set { this[tableQuestionSets.NameColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public string Description
            {
                get { return ((string) (this[tableQuestionSets.DescriptionColumn])); }
                set { this[tableQuestionSets.DescriptionColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int NumberOfQuestionsToPick
            {
                get { return ((int) (this[tableQuestionSets.NumberOfQuestionsToPickColumn])); }
                set { this[tableQuestionSets.NumberOfQuestionsToPickColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int TimeLimit
            {
                get
                {
                    try
                    {
                        return ((int) (this[tableQuestionSets.TimeLimitColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException(
                            "The value for column \'TimeLimit\' in table \'QuestionSets\' is DBNull.", e);
                    }
                }
                set { this[tableQuestionSets.TimeLimitColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int QuestionTypeId
            {
                get
                {
                    try
                    {
                        return ((int) (this[tableQuestionSets.QuestionTypeIdColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException(
                            "The value for column \'QuestionTypeId\' in table \'QuestionSets\' is DBNull.", e);
                    }
                }
                set { this[tableQuestionSets.QuestionTypeIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int QuestionSubtypeId
            {
                get
                {
                    try
                    {
                        return ((int) (this[tableQuestionSets.QuestionSubtypeIdColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException(
                            "The value for column \'QuestionSubtypeId\' in table \'QuestionSets\' is DBNull.", e);
                    }
                }
                set { this[tableQuestionSets.QuestionSubtypeIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int NumberOfQuestionsInZone1
            {
                get { return ((int) (this[tableQuestionSets.NumberOfQuestionsInZone1Column])); }
                set { this[tableQuestionSets.NumberOfQuestionsInZone1Column] = value; }
            }

            [DebuggerNonUserCode()]
            public int NumberOfQuestionsInZone2
            {
                get { return ((int) (this[tableQuestionSets.NumberOfQuestionsInZone2Column])); }
                set { this[tableQuestionSets.NumberOfQuestionsInZone2Column] = value; }
            }

            [DebuggerNonUserCode()]
            public int NumberOfQuestionsInZone3
            {
                get { return ((int) (this[tableQuestionSets.NumberOfQuestionsInZone3Column])); }
                set { this[tableQuestionSets.NumberOfQuestionsInZone3Column] = value; }
            }

            [DebuggerNonUserCode()]
            public bool IsTimeLimitNull()
            {
                return IsNull(tableQuestionSets.TimeLimitColumn);
            }

            [DebuggerNonUserCode()]
            public void SetTimeLimitNull()
            {
                this[tableQuestionSets.TimeLimitColumn] = Convert.DBNull;
            }

            [DebuggerNonUserCode()]
            public bool IsQuestionTypeIdNull()
            {
                return IsNull(tableQuestionSets.QuestionTypeIdColumn);
            }

            [DebuggerNonUserCode()]
            public void SetQuestionTypeIdNull()
            {
                this[tableQuestionSets.QuestionTypeIdColumn] = Convert.DBNull;
            }

            [DebuggerNonUserCode()]
            public bool IsQuestionSubtypeIdNull()
            {
                return IsNull(tableQuestionSets.QuestionSubtypeIdColumn);
            }

            [DebuggerNonUserCode()]
            public void SetQuestionSubtypeIdNull()
            {
                this[tableQuestionSets.QuestionSubtypeIdColumn] = Convert.DBNull;
            }

            [DebuggerNonUserCode()]
            public TestContentsRow[] GetTestContentsRows()
            {
                return ((TestContentsRow[]) (base.GetChildRows(Table.ChildRelations["QuestionSetsTestContents"])));
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TestContentsRow : DataRow
        {
            private TestContentsDataTable tableTestContents;

            [DebuggerNonUserCode()]
            internal TestContentsRow(DataRowBuilder rb) :
                base(rb)
            {
                tableTestContents = ((TestContentsDataTable) (Table));
            }

            [DebuggerNonUserCode()]
            public int TestId
            {
                get { return ((int) (this[tableTestContents.TestIdColumn])); }
                set { this[tableTestContents.TestIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public int QuestionSetId
            {
                get { return ((int) (this[tableTestContents.QuestionSetIdColumn])); }
                set { this[tableTestContents.QuestionSetIdColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public byte QuestionSetOrder
            {
                get { return ((byte) (this[tableTestContents.QuestionSetOrderColumn])); }
                set { this[tableTestContents.QuestionSetOrderColumn] = value; }
            }

            [DebuggerNonUserCode()]
            public TestsRow TestsRow
            {
                get { return ((TestsRow) (GetParentRow(Table.ParentRelations["TestsTestContents"]))); }
                set { SetParentRow(value, Table.ParentRelations["TestsTestContents"]); }
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow QuestionSetsRow
            {
                get { return ((QuestionSetsRow) (GetParentRow(Table.ParentRelations["QuestionSetsTestContents"]))); }
                set { SetParentRow(value, Table.ParentRelations["QuestionSetsTestContents"]); }
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TestsRowChangeEvent : EventArgs
        {
            private TestsRow eventRow;

            private DataRowAction eventAction;

            [DebuggerNonUserCode()]
            public TestsRowChangeEvent(TestsRow row, DataRowAction action)
            {
                eventRow = row;
                eventAction = action;
            }

            [DebuggerNonUserCode()]
            public TestsRow Row
            {
                get { return eventRow; }
            }

            [DebuggerNonUserCode()]
            public DataRowAction Action
            {
                get { return eventAction; }
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class QuestionSetsRowChangeEvent : EventArgs
        {
            private QuestionSetsRow eventRow;

            private DataRowAction eventAction;

            [DebuggerNonUserCode()]
            public QuestionSetsRowChangeEvent(QuestionSetsRow row, DataRowAction action)
            {
                eventRow = row;
                eventAction = action;
            }

            [DebuggerNonUserCode()]
            public QuestionSetsRow Row
            {
                get { return eventRow; }
            }

            [DebuggerNonUserCode()]
            public DataRowAction Action
            {
                get { return eventAction; }
            }
        }

        [GeneratedCode("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TestContentsRowChangeEvent : EventArgs
        {
            private TestContentsRow eventRow;

            private DataRowAction eventAction;

            [DebuggerNonUserCode()]
            public TestContentsRowChangeEvent(TestContentsRow row, DataRowAction action)
            {
                eventRow = row;
                eventAction = action;
            }

            [DebuggerNonUserCode()]
            public TestContentsRow Row
            {
                get { return eventRow; }
            }

            [DebuggerNonUserCode()]
            public DataRowAction Action
            {
                get { return eventAction; }
            }
        }
    }
}

#pragma warning restore 1591